apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-scraper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-scraper
  template:
    metadata:
      labels:
        app: web-scraper
    spec:
      containers:
      - name: web-scraper
        image: web-scraper:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
