apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
      - name: data-processor
        image: data-processor:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: data-processor-config
        volumeMounts:
        - name: data-processor-data
          mountPath: /data/processor
      volumes:
      - name: data-processor-data
        persistentVolumeClaim:
          claimName: data-processor-data-pvc
