apiVersion: v1
kind: ConfigMap
metadata:
  name: data-processor-config
data:
  rabbitmq_host: "rabbitmq"
  rabbitmq_port: "5672"
  rabbitmq_user: "user"
  rabbitmq_password: "password"
  processing_interval: "30"
